#!/bin/bash

 while true; do

 if pacman -Qs android-tools | grep -q 'android-tools'; then
    if adb devices | grep -q "device"; then
        echo -e "\n"

        echo "Please enter the target directory of the backup (example : /path/to/phone/backup/)."
        read -r BackupPath

        echo -e "\n"
        echo "Backup starting..."
        adb backup -apk -shared -all -f "$BackupPath"
        adb pull /sdcard/ "$BackupPath"
        mv "$BackupPath"/sdcard/ "$BackupPath"/PhoneBackup

        echo -e "\n"
        echo "Phone backup complete !"
        exit
    else
        echo -e "\n"
        echo "Your device is not accessible. Did you allow USB debugging ?"
        exit
    fi

 else
    echo -e "\n"

 echo "This program requires the 'android-tools' package to be installed on your system."
 echo "Install now ?"
 select yn in "Yes" "No"; do
    case $yn in
        "Yes" ) pacman -S android-tools;;
        "No" ) exit;;
    esac
 done

 fi
 done
